version: "3"
services:
  app:
    image: 'ghcr.io/horyu1234/spring-boot-admin:master'
    restart: always
    ports:
      # Public HTTP Port:
      - '10001:80'
    volumes:
      - /home/horyu/spring-boot-admin/application.yml:/application.yml